# ==========================================
# CONEXÃO COM O BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/txsoft_db
spring.datasource.username=postgres
spring.datasource.password=0070

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE (ORM)
# ==========================================
# O 'update' faz o Spring Boot criar e atualizar as tabelas automaticamente para nós
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false